version: '3.9'
services:
    app:
        image: hendisantika/laravel:${IMAGE_VER}
        container_name: laravel
        restart: unless-stopped
        tty: true
        volumes:
            - .env:/var/www/.env
        networks:
            - laravel-net

    nginx:
        image: hendisantika/laravel-nginx:${IMAGE_VER}
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8002:80"
        depends_on:
            - app
        networks:
            - laravel-net

#Docker Networks
networks:
    laravel-net:
        driver: bridge
