name: Deploy Application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/dockerfile/app.Dockerfile
          push: true
          tags: hendisantika/laravel:${{ github.run_number }}

      - name: Build and push nginx image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/dockerfile/nginx.Dockerfile
          push: true
          tags: hendisantika/laravel-nginx:${{ github.run_number }}

  deployment:
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          #          password: ${{ secrets.SSH_PASSWORD}}
          port: ${{ secrets.SSH_PORT  }}
          script: |
            whoami
            export IMAGE_VER=${{ github.run_number }}
            #                        fetch-depth: 1
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            cd ~/app/laravel/laravel-upload-photo2 && git checkout -b main
            #            cd ~/app/laravel/ && git checkout -b dev
            git pull origin main
            docker compose build
            docker compose up -d
